# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapchat_activation_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsnapchat_activation_api.proto\x12\x17snapchat.activation.api\"Z\n\x14\x43heckUsernameRequest\x12\n\n\x02ww\x18\x01 \x01(\t\x12\x0e\n\x06unused\x18\x03 \x01(\r\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x12\n\nsession_id\x18\x05 \x01(\t\"I\n\x15\x43heckUsernameResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\r\x12\x1a\n\x12suggested_username\x18\x02 \x01(\t2\x88\x01\n\x16SuggestUsernameService\x12n\n\rCheckUsername\x12-.snapchat.activation.api.CheckUsernameRequest\x1a..snapchat.activation.api.CheckUsernameResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snapchat_activation_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKUSERNAMEREQUEST._serialized_start=58
  _CHECKUSERNAMEREQUEST._serialized_end=148
  _CHECKUSERNAMERESPONSE._serialized_start=150
  _CHECKUSERNAMERESPONSE._serialized_end=223
  _SUGGESTUSERNAMESERVICE._serialized_start=226
  _SUGGESTUSERNAMESERVICE._serialized_end=362
# @@protoc_insertion_point(module_scope)
